// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh3hxnwNcok3pCrP7hP7nYEiPZccQ3bZc',
    appId: '1:592824834971:web:05442c7621b84ace6b5f3e',
    messagingSenderId: '592824834971',
    projectId: 'conta-azul-flutter',
    authDomain: 'conta-azul-flutter.firebaseapp.com',
    storageBucket: 'conta-azul-flutter.appspot.com',
    measurementId: 'G-V6WSE952P4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR7OiaXIEEshJbIWAf5NQeb7bH0Gosy7w',
    appId: '1:592824834971:android:9ac8b685e0b7199c6b5f3e',
    messagingSenderId: '592824834971',
    projectId: 'conta-azul-flutter',
    storageBucket: 'conta-azul-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl51Dpy3plmk7BQ3USD8ySJ_BG7DpwqFM',
    appId: '1:592824834971:ios:bdaf9208c58efce26b5f3e',
    messagingSenderId: '592824834971',
    projectId: 'conta-azul-flutter',
    storageBucket: 'conta-azul-flutter.appspot.com',
    iosBundleId: 'com.contaazul.fluttertest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl51Dpy3plmk7BQ3USD8ySJ_BG7DpwqFM',
    appId: '1:592824834971:ios:bdaf9208c58efce26b5f3e',
    messagingSenderId: '592824834971',
    projectId: 'conta-azul-flutter',
    storageBucket: 'conta-azul-flutter.appspot.com',
    iosBundleId: 'com.contaazul.fluttertest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh3hxnwNcok3pCrP7hP7nYEiPZccQ3bZc',
    appId: '1:592824834971:web:ac69df82231eb4366b5f3e',
    messagingSenderId: '592824834971',
    projectId: 'conta-azul-flutter',
    authDomain: 'conta-azul-flutter.firebaseapp.com',
    storageBucket: 'conta-azul-flutter.appspot.com',
    measurementId: 'G-KFQZW40KFZ',
  );
}
